version: "3.8"

services:
  app:
    restart: unless-stopped
    build:
      .
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - internal-network
      - external-network
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        max-size: 100m
  postgres:
    image: postgres:12.6
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data
    networks:
      - internal-network

networks:
  internal-network:
    internal: true
  external-network:
